# Generated by Django 5.0.4 on 2024-04-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankist', '0002_alter_account_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
    ]
